spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

  datasource:
    url: "jdbc:mysql://localhost/Tour" 
    username: "root"
    password: "" # MySQL 비밀번호 설정
    driver-class-name: com.mysql.cj.jdbc.Driver